### ISSUE TITLE
rotate chevron icon of accordion 

### ISSUE THREAD

**Issue by vinod911** [pkerspe/ckeditor-bootstrap-collapsibleItem#15]
Hi when in php CKeditor we add Accordion the drop down arrow how can we change?

**Comment by pkerspe** [comment]
change line 6 in plugin.js:
`<span class="glyphicon glyphicon-chevron-down">`
and set your desired icon there.
Or you could overwrite the class "glyphicon-chevron-down" in your custom css, you should use a rather specific selector though to prevent side effects with other usages of "glyphicon-chevron-down"

**Comment by vinod911** [comment]
Hi Paul,

No no i don't mean to change  the icon.

glyphicon-chevron-down is fine 

when i click the accordion after clicking the glyphicon-chevron-down should change to glyphicon-chevron-up 

hope you understand what i am trying to say

**Comment by pkerspe** [comment]
ok, got you.
You would need to write some more js code to do that.
Since this is a more general Bootstrap question, here ist an example how to realize that in Bootstrap via js:
https://www.tutorialrepublic.com/twitter-bootstrap-tutorial/bootstrap-accordion.php

Note: this example uses FontAwesome classes so you need to replace that with the classe name for glyphicon (replace "fa" selectors with "glyphicon"). Also need to replace the other classes like "card-header" with "panel-title" etc...the example is basically leading the way but cannot directly be used via copy and paste obviously. If you got it working I would be happy about a pull requesst or you paste your changes here, so I can intergrate it into the code

**Comment by vinod911** [comment]
ok so do I need to make any changes in your JS (plugin.js) or just css  ? can you please help

**Comment by pkerspe** [comment]
you would need to update the plugin.js more specifically the "init: function () " part. There you need to register the event listener to listen for toggling of the header part and replace the css class when the panel is opened/closed.

**Comment by vinod911** [comment]
aha ok so in that it will be done right ?

**Comment by pkerspe** [comment]
yeah well, it is a bit tricky, actually this function prepares the needed html element, takes care of the unique naming etc. you need to create a script block  for each widget that has been placed in the content and within that script block to register the event listener. Honestly I would need to invest more time to get back into this code, since it has been a wile I worked on it the last time.
I can only point out the rough direction, but not a specific solution at the time

**Comment by vinod911** [comment]
aha understand thanks for your help...it would be actually great if in the addon it was that way so the users worldwide do not tweak the code .. thank you so much for your help...if in future you update this ADD ON for this feature please let me know... thanks god bless!!
